server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s ipv6=off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        set $api_upstream host.docker.internal:3000;
        proxy_pass http://$api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
